### ISSUE TITLE
Build problem with next.js

### ISSUE THREAD

**Issue by landsman** [greg-schrammel/react-firebaseui-localized#12]
- next.js version: 10.2.3
- reactjs version: 17.0.1

```
error - ./node_modules/react-firebaseui-localized/index.js
Module parse failed: Unexpected token (31:4)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
|   return (
>     <>
|       <div ref={container} id={FIREBASEUI_CONTAINER_ID} />
|     </>
/Users/landsman/projects/xxx/node_modules/react-firebaseui-localized/index.js:1
import React, { useEffect, useRef } from "react";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at eval (webpack-internal:///react-firebaseui-localized:1:18)
 ```

**Comment by greg-schrammel** [comment]
Hey, can you make a reproducible demo?

**Comment by rincotz** [comment]
transpiling the jsx into plain javascript may solve the problem

https://github.com/greg-schrammel/react-firebaseui-localized/pull/13

**Comment by Rijast** [comment]
Hi, Any solution for this yet? I am getting the same issue with next.js 11.0.1 and React 17.0.2. Thanks!!

`error - ./node_modules/react-firebaseui-localized/index.js
Module parse failed: Unexpected token (31:4)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
|   return (
>     <div>
|       <link
|         type="text/css"
/xxx/node_modules/react-firebaseui-localized/index.js:1
import React, { useEffect, useRef } from "react";
^^^^^^`

**Comment by greg-schrammel** [comment]
can you please make a lil reproducible code sandbox?

**Comment by Rijast** [comment]
Sure here you go: https://codesandbox.io/s/react-firebaseui-localized-test-f96tr

I haven't included the Firebase creds etc but that doesn't effect it.

Really appreciate you looking at this, I really like your approach with the CDN and it's a nice solution! 

Thanks

<img width="1548" alt="Screenshot 2021-09-01 at 09 58 08" src="https://user-images.githubusercontent.com/6334657/131643806-5af34fcb-ccf3-4082-8058-957e03a4a886.png">

**Comment by greg-schrammel** [comment]
omg I'm sorry for this, I had uploaded the file to npm without building it 😅

it's fixed now, please update to version 1.2.1

**Comment by chwadvocates** [comment]
@greg-schrammel thanks a lot - works great!

**Comment by Rijast** [comment]
@greg-schrammel works great! thanks a lot!
