### ISSUE TITLE
[bug] Using firebase auth emulator

### ISSUE THREAD

**Issue by drosi94** [greg-schrammel/react-firebaseui-localized#14]
There is an issue when this package is used with firebase auth emulator. 

![Screenshot 2021-09-06 at 8 18 46 PM](https://user-images.githubusercontent.com/3253526/132248421-b00ae272-09c5-46f4-9562-bfb78821f4aa.png)

**Comment by greg-schrammel** [comment]
this is an issue with FirebaseUI please take a loot at https://github.com/firebase/firebaseui-web/issues/778
