### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by zyxneo** [greg-schrammel/react-firebaseui-localized#6]
Dear @greg-schrammel !

Many thanks for developing this package! We wanted to use it, but noticed, that there are some tiny things missing for our needs.

As feedback, we recommend adding the RTL CSS conditionally, e.g.:
```html
      <link
        type="text/css"
        rel="stylesheet"
        href={`https://www.gstatic.com/firebasejs/ui/${firebaseVersion}/firebase-ui-auth${
          RtlLangs.includes(lang) ? '-rtl' : ''
        }.css`}
      />
```

Many thanks again!
BR!

**Comment by greg-schrammel** [comment]
Hey! sorry for the delay, I made this a long time ago and forgot about it.  

I don't think it's in this package scope to check if the language is rtl or not, so I just added it as a prop (it's published) 

Any other issue I will be glad to review a pr, thanks for the feedback!

**Comment by zyxneo** [comment]
Hi!

So this was the change: https://github.com/greg-schrammel/react-firebaseui-localized/commit/51b8564fd30e05e5b79b712e219a65c816362f90 #51b8564fd30e05e5b79b712e219a65c816362f90

Many thanks!
